version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user_1
      - POSTGRES_PASSWORD=P@ssW0rd1
      - POSTGRES_DB_NAME=pg_db
      - POSTGRES_PORT=5432
    volumes:
      - ./db/01-init.sh:/docker-entrypoint-initdb.d/01-init.sh
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=user_1
      - POSTGRES_PASSWORD=P@ssW0rd1
      - POSTGRES_DB_NAME=pg_db
      - POSTGRES_PORT=5432
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json