version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user_1
      POSTGRES_PASSWORD: P@ssW0rd1
      POSTGRES_DB: pg_db
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    develop:
      watch:
        - action: sync
          path: ./
          target: /usr/src/app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json